name: Pack and Publish

on:
  # only for debug/troubleshooting
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  VERSION: ${{ github.event_name != 'workflow_dispatch' && github.ref_name || '0.0.0-debug' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.x"

      - name: Pack
        working-directory: ./project-templates
        run: dotnet pack -p:PackageVersion=${{ env.VERSION }} -o artifacts

      - name: Publish
        if: ${{ github.event_name != 'workflow_dispatch' }}
        working-directory: ./project-templates/artifacts
        run: dotnet nuget push *.nupkg -s 'https://api.nuget.org/v3/index.json' --skip-duplicate -n -k ${{ secrets.NUGET_API_KEY }}
